'''
ALGORITIMO 'Media de notas'

DECLARE 'Nome'
DECLARE N1, N2, N3
DECLARE MENSAGEM_APROVADO, MENSAGEM_PROVA_FINAL, MENSAGEM_REPROVADO LITERAL

leia N1, N2, N3

MEDIA <- (N1 + N2 + N3)/3

MENSAGEM_APROVADO <- "Aprovado"
MENSAGEM_PROVA_FINAL <- "Prova Final"
MENSAGEM_REPROVADO <- "Reprovado"

se MEDIA >= 7.0
	então ESCREVA MENSAGEM_APROVADO "Aprovado"

senão se MEDIA > 3.9 E MEDIA < 7.0
	então ESCREVA MENSAGEM_PROVA_FINAL "Prova Final"

senão
	então ESCREVA MENSAGEM_REPROVADO "Reprovado"

FIM_ALGORITMO
'''